web:
    build: .
    dockerfile: Dockerfile
    command: mix phoenix.server
    environment:
        - MIX_ENV=dev
        - PORT=4000
        - PG_HOST=postgres
        - PG_USERNAME=postgres
        - PG_DATABASE=postgres
    volumes:
        - .:/app
    ports:
        - "4000:4000"
    links:
        - postgres

postgres:
    image: mdillon/postgis:9.6
    ports:
        - "5432"

